name: Contracts Build

on:
  push:
  pull_request:

concurrency:
  group: contracts-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Checkout the pull request head
          ref: ${{ github.head_ref || github.ref }}
          submodules: recursive

      - name: Cache Foundry
        uses: actions/cache@v4
        with:
          path: ~/.foundry
          key: foundry-${{ runner.os }}-${{ hashFiles('foundry.toml') }}

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source ~/.bashrc
          foundryup

      - name: Forge build
        run: forge build

